<a href="https://colab.research.google.com/github/adarshraa-phy/Pandas/blob/main/pandas_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Create dataframe using python dictionary

In [ ]:
#using method data frame
import pandas as pd
emp={'id':[101,102,103,104,105],
     'Name':['deepak','shyam','arum','manu','jeena'],
     'Age':[25,22,24,20,27],
     'salary':[25000,30000,150000,10000,30000]
     }
df=pd.DataFrame(emp)
df

    id    Name  Age  salary
0  101  deepak   25   25000
1  102   shyam   22   30000
2  103    arum   24  150000
3  104    manu   20   10000
4  105   jeena   27   30000

Create dataframe using python tuple list

In [ ]:
import pandas as pd
emp_data=[(101,'deepak',25,35000),
          (102,'shyam',22,30000),
          (103,'arun',24,150000),
          (104,'manu',20,10000),
          (105,'jeena',27,30000)
          ]
df=pd.DataFrame(emp_data,columns=['id','name','age','salary'])
df

    id    name  age  salary
0  101  deepak   25   35000
1  102   shyam   22   30000
2  103    arun   24  150000
3  104    manu   20   10000
4  105   jeena   27   30000

Create Dataframe using a list of dictionaries

In [ ]:
import pandas as pd
emp_data_list=[{'id':101,'name':'deepak','age':25,'salary':25000},
               {'id':102,'name':'shyam','age':22,'salary':30000},
               {'id':103,'name':'arun','age':24,'salary':150000},
               {'id':104,'name':'manu','age':20,'salary':10000},
               {'id':105,'name':'jeena','age':27,'salary':30000}
               ]

df=pd.DataFrame(emp_data_list)
df

    id    name  age  salary
0  101  deepak   25   25000
1  102   shyam   22   30000
2  103    arun   24  150000
3  104    manu   20   10000
4  105   jeena   27   30000

In [ ]:
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Dataset/data (2).csv')
df

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

#Pandas Series

In [ ]:
import pandas as pd
a=[1,7,2]
myvar=pd.Series(a)
print(myvar)

0    1
1    7
2    2
dtype: int64

#Labels

In [ ]:
import pandas as pd
a=[1,7,2]
myvar=pd.Series(a)
print(myvar[0])

1

#create labels

In [ ]:
import pandas as pd
a=[1,7,2]
myvar=pd.Series(a,index=["x","y","z"])
print(myvar)

x    1
y    7
z    2
dtype: int64

In [ ]:
import pandas as pd
a=[1,7,2]
myvar=pd.Series(a,index=["x","y","z"])
print(myvar["y"])

7

Key value objects as series

In [ ]:
import pandas as pd
calories={"day1":420,"day2":380,"day3":390}
myvar=pd.Series(calories)
print(myvar)

day1    420
day2    380
day3    390
dtype: int64

In [ ]:
import pandas as pd
calories={"day1":420,"day2":380,"day3":390}
myvar=pd.Series(calories,index=["day1","day2"])
print(myvar)

day1    420
day2    380
dtype: int64

In [ ]:
import pandas as pd
df=pd.read_csv("/content/employee_dataset.csv")
df

    ID     Name Department  Salary
0  101    Alice         HR   50000
1  102      Bob    Finance   60000
2  103  Charlie         IT   70000
3  104    David  Marketing   55000
4  105      Eva         IT   72000

read text file

In [ ]:
import pandas as pd
data=pd.read_csv('/content/text_output.csv',delimeter='/t')
print(data)

TypeError: read_csv() got an unexpected keyword argument 'delimeter'

read excel file

In [ ]:
import pandas as pd
df=pd.read_excel('/content/employee_datasetnew.xls')
df

    ID     Name Department  Salary
0  101    Alice         HR   50000
1  102      Bob    Finance   60000
2  103  Charlie         IT   70000
3  104    David  Marketing   55000
4  105      Eva         IT   72000

Skip the unnecessary header or add yours

In [ ]:
data=pd.read_csv('/content/employee_dataset.csv',skiprows=1)
print(data)

   101    Alice         HR  50000
0  102      Bob    Finance  60000
1  103  Charlie         IT  70000
2  104    David  Marketing  55000
3  105      Eva         IT  72000

In [ ]:
#if you don't have header in your file and you want to add some column header

data=pd.read_csv('/content/drive/MyDrive/updated_data.csv',header=None,names=['Name','Age','Occupation'])#if you want to replace your column with NaN by specific to column
data_1=pd.read_csv('/content/drive/MyDrive/updated_data.csv',na_values={'Age':['n.a','not available'],'Occupation':['n.a','not available']})
print(data)
print(data_1)

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/updated_data.csv'

In [ ]:
#Read a limited number of rows from the top of the file
data=pd.read_csv('/content/employee_dataset.csv',nrows
=1)
print(data)

    ID   Name Department  Salary
0  101  Alice         HR   50000

In [ ]:
#Replace all unwanted value with NaN
import numpy as np
data=pd.read_csv('/content/employee_dataset.csv')
nwanted_values = ['not available age', '-', 'unknown', '', 'N/A']

#Using Converters

Using converters to convert data using conditions

In [ ]:
def convert(occupation):
  if occupation=='doctor':
    return 'teacher'
  else:
    return occupation
    data=pd.read_csv('/content/employee_dataset.csv',converters={'occupation':convert})
print(data)

    ID     Name Department  Salary
0  101    Alice         HR   50000
1  102      Bob    Finance   60000
2  103  Charlie         IT   70000
3  104    David  Marketing   55000
4  105      Eva         IT   72000

Write to Excel

In [ ]:
#write excel

data.to_excel('/content/drive/MyDrive/Colab Notebooks/new.xlsx')
data

    ID     Name Department  Salary
0  101    Alice         HR   50000
1  102      Bob    Finance   60000
2  103  Charlie         IT   70000
3  104    David  Marketing   55000
4  105      Eva         IT   72000

Write two data frames in a single excel file

In [ ]:
#Using write ExcelWriter() method

import pandas as pd

# Example DataFrames
data1 = pd.DataFrame({
    'Name': ['John', 'Alice'],
    'Age': [23, 30]
})

data2 = pd.DataFrame({
    'Product': ['Pen', 'Notebook'],
    'Price': [10, 50]
})

with pd.ExcelWriter('/content/drive/MyDrive/Colab Notebooks/new2.xlsx')as wr:
  data1.to_excel(wr,sheet_name='Sheet1')
  data2.to_excel(wr,sheet_name='Sheet2')

In [ ]:
import pandas as pd

data = {
    "index": [
        0, 1, 2, 3, 4,
        5, 6, 7, 8, 9
    ],
    "airline": [
        "SpiceJet", "SpiceJet", "AirAsia", "Vistara", "Vistara",
        "Vistara", "Vistara", "Vistara", "Vistara", "Vistara"
    ],
    "flight": [
        "SG-8709", "SG-8157", "I5-764", "UK-995", "UK-963",
        "UK-822", "UK-826", "UK-832", "UK-828", "UK-822"
    ],
    "source_city": [
        "Delhi", "Delhi", "Delhi", "Delhi", "Delhi",
        "Chennai", "Chennai", "Chennai", "Chennai", "Chennai"
    ],
    "departure_time": [
        "Evening", "Early_Morning", "Early_Morning", "Morning", "Morning",
        "Morning", "Afternoon", "Early_Morning", "Early_Morning", "Morning"
    ],
    "stops": [
        "zero", "zero", "zero", "zero", "zero",
        "one", "one", "one", "one", "one"
    ],
    "arrival_time": [
        "Night", "Morning", "Early_Morning", "Afternoon", "Morning",
        "Evening", "Night", "Night", "Evening", "Evening"
    ],
    "destination_city": [
        "Mumbai", "Mumbai", "Mumbai", "Mumbai", "Mumbai",
        "Hyderabad", "Hyderabad", "Hyderabad", "Hyderabad", "Hyderabad"
    ],
    "class": [
        "Economy", "Economy", "Economy", "Economy", "Economy",
        "Business", "Business", "Business", "Business", "Business"
    ],
    "duration": [
        2.17, 2.33, 2.17, 2.25, 2.33,
        10.08, 10.42, 13.83, 10.00, 10.08
    ],
    "days_left": [
        1, 1, 1, 1, 1,
        49, 49, 49, 49, 49
    ],
    "price": [
        5953, 5953, 5956, 5955, 5955,
        69265, 77105, 79099, 81585, 81585
    ]
}

df = pd.DataFrame(data)
df

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
5,5,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
6,6,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
7,7,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
8,8,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
9,9,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [ ]:
df.head()

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

In [ ]:
df.head(3)

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956

In [ ]:
df.tail()

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
5,5,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
6,6,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
7,7,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
8,8,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
9,9,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [ ]:
df.tail(3)

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
7,7,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
8,8,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
9,9,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [ ]:
df.shape

(10, 12)

In [ ]:
df.info()  #to print details about the data,to find null values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   index             10 non-null     int64
 1   airline           10 non-null     object
 2   flight            10 non-null     object
 3   source_city       10 non-null     object
 4   departure_time    10 non-null     object
 5   stops             10 non-null     object
 6   arrival_time      10 non-null     object
 7   destination_city  10 non-null     object
 8   class             10 non-null     object
 9   duration          10 non-null     float64
 10  days_left         10 non-null     int64
 11  price             10 non-null     int64
dtypes: float64(1), int64(3), object(8)
memory usage: 1.1+ KB

In [ ]:
df.describe() #print all statistical results

          index   duration  days_left         price
count  10.00000  10.000000  10.000000     10.000000
mean    4.50000   6.566000  25.000000  41841.100000
std     3.02765   4.681793  25.298221  37979.812493
min     0.00000   2.170000   1.000000   5953.000000
25%     2.25000   2.270000   1.000000   5955.000000
50%     4.50000   6.165000  25.000000  37610.500000
75%     6.75000  10.080000  49.000000  78600.500000
max     9.00000  13.830000  49.000000  81585.000000

In [ ]:
df[['airline','price']] #to selsect multiple column( 2 dimension tabledata.describe() #print all statistical results)

    airline  price
0  SpiceJet   5953
1  SpiceJet   5953
2   AirAsia   5956
3   Vistara   5955
4   Vistara   5955
5   Vistara  69265
6   Vistara  77105
7   Vistara  79099
8   Vistara  81585
9   Vistara  81585

In [ ]:
df[5:20]

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
5,5,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
6,6,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
7,7,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
8,8,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
9,9,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [ ]:
df[5:100:4]

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
5,5,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
9,9,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [ ]:
df['price'].mean()

np.float64(41841.1)

In [ ]:
df[(df['price'] > 10000) & (df['price'] < 20000)]

Empty DataFrame
Columns: [index, airline, flight, source_city, departure_time, stops, arrival_time, destination_city, class, duration, days_left, price]
Index: []

In [ ]:
df.set_index(df['index'])

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
index,,,,,,,,,,,,
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
5,5,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
6,6,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
7,7,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
8,8,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
9,9,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   index             10 non-null     int64
 1   airline           10 non-null     object
 2   flight            10 non-null     object
 3   source_city       10 non-null     object
 4   departure_time    10 non-null     object
 5   stops             10 non-null     object
 6   arrival_time      10 non-null     object
 7   destination_city  10 non-null     object
 8   class             10 non-null     object
 9   duration          10 non-null     float64
 10  days_left         10 non-null     int64
 11  price             10 non-null     int64
dtypes: float64(1), int64(3), object(8)
memory usage: 1.1+ KB

In [ ]:
df.fillna(34)

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
5,5,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
6,6,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
7,7,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
8,8,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
9,9,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   index             10 non-null     int64
 1   airline           10 non-null     object
 2   flight            10 non-null     object
 3   source_city       10 non-null     object
 4   departure_time    10 non-null     object
 5   stops             10 non-null     object
 6   arrival_time      10 non-null     object
 7   destination_city  10 non-null     object
 8   class             10 non-null     object
 9   duration          10 non-null     float64
 10  days_left         10 non-null     int64
 11  price             10 non-null     int64
dtypes: float64(1), int64(3), object(8)
memory usage: 1.1+ KB

In [ ]:
df.dropna()

    ID     Name Department  Salary
0  101    Alice         HR   50000
1  102      Bob    Finance   60000
2  103  Charlie         IT   70000
3  104    David  Marketing   55000
4  105      Eva         IT   72000

#Replace Function

replace()

In [ ]:
data=pd.read_csv('/content/employee_dataset.csv')
df=data

In [ ]:
import numpy as np
df.replace("Alice","adarsh")  #replace the value with nan

    ID     Name Department  Salary
0  101   adarsh         HR   50000
1  102      Bob    Finance   60000
2  103  Charlie         IT   70000
3  104    David  Marketing   55000
4  105      Eva         IT   72000

In [ ]:
#replace values with specific to columns
df.replace({'Name':'Alice','Age':25.0,'Salary':50000.0},np.nan)

    ID     Name Department   Salary
0  101      NaN         HR      NaN
1  102      Bob    Finance  60000.0
2  103  Charlie         IT  70000.0
3  104    David  Marketing  55000.0
4  105      Eva         IT  72000.0

loading data set

In [ ]:
import pandas as pd
df

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
5,5,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
6,6,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
7,7,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
8,8,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
9,9,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

Group by

In [ ]:
group_result=df.groupby('airline')#group by airlines
list(group_result)

[('AirAsia',
     index  airline  flight source_city departure_time stops   arrival_time  \
  2      2  AirAsia  I5-764       Delhi  Early_Morning  zero  Early_Morning

    destination_city    class  duration  days_left  price
  2           Mumbai  Economy      2.17          1   5956  ),
 ('SpiceJet',
     index   airline   flight source_city departure_time stops arrival_time  \
  0      0  SpiceJet  SG-8709       Delhi        Evening  zero        Night
  1      1  SpiceJet  SG-8157       Delhi  Early_Morning  zero      Morning

    destination_city    class  duration  days_left  price
  0           Mumbai  Economy      2.17          1   5953
  1           Mumbai  Economy      2.33          1   5953  ),
 ('Vistara',
     index  airline  flight source_city departure_time stops arrival_time  \
  3      3  Vistara  UK-995       Delhi        Morning  zero    Afternoon
  4      4  Vistara  UK-963       Delhi        Morning  zero      Morning
  5      5  Vistara  UK-822     Chennai        Morning   one      Evening
  6      6  Vistara  UK-826     Chennai      Afternoon   one        Night
  7      7  Vistara  UK-832     Chennai  Early_Morning   one        Night
  8      8  Vistara  UK-828     Chennai  Early_Morning   one      Evening
  9      9  Vistara  UK-822     Chennai        Morning   one      Evening

    destination_city     class  duration  days_left  price
  3           Mumbai   Economy      2.25          1   5955
  4           Mumbai   Economy      2.33          1   5955
  5        Hyderabad  Business     10.08         49  69265
  6        Hyderabad  Business     10.42         49  77105
  7        Hyderabad  Business     13.83         49  79099
  8        Hyderabad  Business     10.00         49  81585
  9        Hyderabad  Business     10.08         49  81585  )]

In [ ]:
group_result.get_group('Vistara') # airline with specific name

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
5,5,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
6,6,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
7,7,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
8,8,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
9,9,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [ ]:
#using forloop gruoping by airlines,flight,source city
for flight,source_city in group_result:
  print(flight)
  print(source_city)

AirAsia
   index  airline  flight source_city departure_time stops   arrival_time  \
2      2  AirAsia  I5-764       Delhi  Early_Morning  zero  Early_Morning

  destination_city    class  duration  days_left  price
2           Mumbai  Economy      2.17          1   5956
SpiceJet
   index   airline   flight source_city departure_time stops arrival_time  \
0      0  SpiceJet  SG-8709       Delhi        Evening  zero        Night
1      1  SpiceJet  SG-8157       Delhi  Early_Morning  zero      Morning

  destination_city    class  duration  days_left  price
0           Mumbai  Economy      2.17          1   5953
1           Mumbai  Economy      2.33          1   5953
Vistara
   index  airline  flight source_city departure_time stops arrival_time  \
3      3  Vistara  UK-995       Delhi        Morning  zero    Afternoon
4      4  Vistara  UK-963       Delhi        Morning  zero      Morning
5      5  Vistara  UK-822     Chennai        Morning   one      Evening
6      6  Vistara  UK-826     Chennai      Afternoon   one        Night
7      7  Vistara  UK-832     Chennai  Early_Morning   one        Night
8      8  Vistara  UK-828     Chennai  Early_Morning   one      Evening
9      9  Vistara  UK-822     Chennai        Morning   one      Evening

  destination_city     class  duration  days_left  price
3           Mumbai   Economy      2.25          1   5955
4           Mumbai   Economy      2.33          1   5955
5        Hyderabad  Business     10.08         49  69265
6        Hyderabad  Business     10.42         49  77105
7        Hyderabad  Business     13.83         49  79099
8        Hyderabad  Business     10.00         49  81585
9        Hyderabad  Business     10.08         49  81585

Group operations

In [ ]:
group_result.max() # oro  airlinilum max value

,index,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
airline,,,,,,,,,,,
AirAsia,2,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
SpiceJet,1,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.33,1,5953
Vistara,9,UK-995,Delhi,Morning,zero,Night,Mumbai,Economy,13.83,49,81585

In [ ]:
group_result.get_group('Vistara').max()

index                     9
airline             Vistara
flight               UK-995
source_city           Delhi
departure_time      Morning
stops                  zero
arrival_time          Night
destination_city     Mumbai
class               Economy
duration              13.83
days_left                49
price                 81585
dtype: object

group by multiple columns

In [ ]:
#group by source_city,destination_city
grp=df.groupby(['flight','source_city'])
list(grp)

[(('I5-764', 'Delhi'),
     index  airline  flight source_city departure_time stops   arrival_time  \
  2      2  AirAsia  I5-764       Delhi  Early_Morning  zero  Early_Morning

    destination_city    class  duration  days_left  price
  2           Mumbai  Economy      2.17          1   5956  ),
 (('SG-8157', 'Delhi'),
     index   airline   flight source_city departure_time stops arrival_time  \
  1      1  SpiceJet  SG-8157       Delhi  Early_Morning  zero      Morning

    destination_city    class  duration  days_left  price
  1           Mumbai  Economy      2.33          1   5953  ),
 (('SG-8709', 'Delhi'),
     index   airline   flight source_city departure_time stops arrival_time  \
  0      0  SpiceJet  SG-8709       Delhi        Evening  zero        Night

    destination_city    class  duration  days_left  price
  0           Mumbai  Economy      2.17          1   5953  ),
 (('UK-822', 'Chennai'),
     index  airline  flight source_city departure_time stops arrival_time  \
  5      5  Vistara  UK-822     Chennai        Morning   one      Evening
  9      9  Vistara  UK-822     Chennai        Morning   one      Evening

    destination_city     class  duration  days_left  price
  5        Hyderabad  Business     10.08         49  69265
  9        Hyderabad  Business     10.08         49  81585  ),
 (('UK-826', 'Chennai'),
     index  airline  flight source_city departure_time stops arrival_time  \
  6      6  Vistara  UK-826     Chennai      Afternoon   one        Night

    destination_city     class  duration  days_left  price
  6        Hyderabad  Business     10.42         49  77105  ),
 (('UK-828', 'Chennai'),
     index  airline  flight source_city departure_time stops arrival_time  \
  8      8  Vistara  UK-828     Chennai  Early_Morning   one      Evening

    destination_city     class  duration  days_left  price
  8        Hyderabad  Business      10.0         49  81585  ),
 (('UK-832', 'Chennai'),
     index  airline  flight source_city departure_time stops arrival_time  \
  7      7  Vistara  UK-832     Chennai  Early_Morning   one        Night

    destination_city     class  duration  days_left  price
  7        Hyderabad  Business     13.83         49  79099  ),
 (('UK-963', 'Delhi'),
     index  airline  flight source_city departure_time stops arrival_time  \
  4      4  Vistara  UK-963       Delhi        Morning  zero      Morning

    destination_city    class  duration  days_left  price
  4           Mumbai  Economy      2.33          1   5955  ),
 (('UK-995', 'Delhi'),
     index  airline  flight source_city departure_time stops arrival_time  \
  3      3  Vistara  UK-995       Delhi        Morning  zero    Afternoon

    destination_city    class  duration  days_left  price
  3           Mumbai  Economy      2.25          1   5955  )]

Concat
it is used to concat two or more dataframes

In [ ]:
import pandas as pd
import pandas as pd
tcs={'id':[101,102,103,104],'name':['Mithun','Dipin','Jose','Rahul'],
     'Age':[25,26,27,29]}

wipro={'id':[101,102,103,104],
       'name':['dev','sreenath','sreerag','shafeel'],
       'age':[24,24,27,26]}

tcs_emp=pd.DataFrame(tcs)
wipro_emp=pd.DataFrame(wipro)
pd.concat([tcs_emp,wipro_emp])

    id      name   Age   age
0  101    Mithun  25.0   NaN
1  102     Dipin  26.0   NaN
2  103      Jose  27.0   NaN
3  104     Rahul  29.0   NaN
0  101       dev   NaN  24.0
1  102  sreenath   NaN  24.0
2  103   sreerag   NaN  27.0
3  104   shafeel   NaN  26.0

In [ ]:
#ignore index-To get common index after concatenation
pd.concat([tcs_emp,wipro_emp],ignore_index=True)

    id      name   Age   age
0  101    Mithun  25.0   NaN
1  102     Dipin  26.0   NaN
2  103      Jose  27.0   NaN
3  104     Rahul  29.0   NaN
4  101       dev   NaN  24.0
5  102  sreenath   NaN  24.0
6  103   sreerag   NaN  27.0
7  104   shafeel   NaN  26.0

In [ ]:
#keys-To provide seperate keys for each concatenate data frames
data=pd.concat([tcs_emp,wipro_emp],keys=['tcs','wipro'])
data

          id      name   Age   age
tcs   0  101    Mithun  25.0   NaN
      1  102     Dipin  26.0   NaN
      2  103      Jose  27.0   NaN
      3  104     Rahul  29.0   NaN
wipro 0  101       dev   NaN  24.0
      1  102  sreenath   NaN  24.0
      2  103   sreerag   NaN  27.0
      3  104   shafeel   NaN  26.0

In [ ]:
#concatenating vertically
data=pd.concat([tcs_emp,wipro_emp],axis=1)


data

    id    name  Age   id      name  age
0  101  Mithun   25  101       dev   24
1  102   Dipin   26  102  sreenath   24
2  103    Jose   27  103   sreerag   27
3  104   Rahul   29  104   shafeel   26

In [ ]:
#cocatinating a dataframe with a series
salary=pd.Series([65000,75000,15000,25000],name='salary')
pd.concat([tcs_emp,salary],axis=1)

    id    name  Age  salary
0  101  Mithun   25   65000
1  102   Dipin   26   75000
2  103    Jose   27   15000
3  104   Rahul   29   25000

#Merge
merge is a process to merge two tables horizontally

In [ ]:
import pandas as pd
tcs={'id':[101,102,103,106],'name':['Mithun','Dipin','Jose','Rahul'],
     'Age':[25,26,27,29]}

wipro={'id':[101,102,103,105],
       'name':['dev','sreenath','sreerag','shafeel'],
       'age':[24,24,27,26]}

tcs_emp=pd.DataFrame(tcs)
wipro_emp=pd.DataFrame(wipro)

tcs_emp=pd.DataFrame(tcs)
tcs_emp

    id    name  Age
0  101  Mithun   25
1  102   Dipin   26
2  103    Jose   27
3  106   Rahul   29

In [ ]:
wipro_emp=pd.DataFrame(wipro)
wipro_emp

    id      name  age
0  101       dev   24
1  102  sreenath   24
2  103   sreerag   27
3  105   shafeel   26

In [ ]:
pd.merge(tcs_emp,wipro_emp,on='id')

    id  name_x  Age    name_y  age
0  101  Mithun   25       dev   24
1  102   Dipin   26  sreenath   24
2  103    Jose   27   sreerag   27

In [ ]:
pd.merge(tcs_emp,wipro_emp,on='id',suffixes=['left','right'])

    id nameleft  Age nameright  age
0  101   Mithun   25       dev   24
1  102    Dipin   26  sreenath   24
2  103     Jose   27   sreerag   27

In [ ]:
pd.merge(tcs_emp,wipro_emp,on='id',suffixes=['left','right'])

    id nameleft  Age nameright  age
0  101   Mithun   25       dev   24
1  102    Dipin   26  sreenath   24
2  103     Jose   27   sreerag   27

In [ ]:
pd.merge(tcs_emp,wipro_emp,on='id',how='outer')#outer join

    id  name_x   Age    name_y   age
0  101  Mithun  25.0       dev  24.0
1  102   Dipin  26.0  sreenath  24.0
2  103    Jose  27.0   sreerag  27.0
3  105     NaN   NaN   shafeel  26.0
4  106   Rahul  29.0       NaN   NaN

In [ ]:
pd.merge(tcs_emp,wipro_emp,on='id',how='outer',indicator=True)

    id  name_x   Age    name_y   age      _merge
0  101  Mithun  25.0       dev  24.0        both
1  102   Dipin  26.0  sreenath  24.0        both
2  103    Jose  27.0   sreerag  27.0        both
3  105     NaN   NaN   shafeel  26.0  right_only
4  106   Rahul  29.0       NaN   NaN   left_only

In [ ]:
pd.merge(tcs_emp,wipro_emp,on='id',how='left') #left join

    id  name_x  Age    name_y   age
0  101  Mithun   25       dev  24.0
1  102   Dipin   26  sreenath  24.0
2  103    Jose   27   sreerag  27.0
3  106   Rahul   29       NaN   NaN

In [ ]:
pd.merge(tcs_emp,wipro_emp,on='id',how='right') #right join

    id  name_x   Age    name_y  age
0  101  Mithun  25.0       dev   24
1  102   Dipin  26.0  sreenath   24
2  103    Jose  27.0   sreerag   27
3  105     NaN   NaN   shafeel   26

Pivot and Pivot table
pivot allows to reshape data frame
pivot table is used to summarize or aggregat

In [ ]:
import pandas as pd
data=pd.read_csv('/content/weather_dataset_100_rows_no_duplicate_index.csv')
data

,Date,City,Temperature,Humidity,Wind Speed (km/h),Weather Condition
0,2025-08-09,Delhi,33.0,80.0,14.0,Partly Cloudy
1,2025-08-01,Delhi,26.0,54.0,8.0,Partly Cloudy
2,2025-08-13,Delhi,NaN,66.0,17.0,Partly Cloudy
3,2025-08-13,Bengaluru,36.0,55.0,16.0,Partly Cloudy
4,2025-08-09,Mumbai,38.0,74.0,19.0,Sunny
...,...,...,...,...,...,...
95,2025-08-05,Bengaluru,34.0,62.0,16.0,Partly Cloudy
96,2025-08-09,Bengaluru,NaN,88.0,16.0,Sunny
97,2025-08-08,Mumbai,27.0,46.0,23.0,Rainy
98,2025-08-04,Delhi,27.0,55.0,8.0,Cloudy
99,2025-08-12,Mumbai,27.0,47.0,15.0,Rainy

In [ ]:
data.pivot_table(index='Date',columns='City',values='Temperature')

City        Bengaluru      Delhi     Mumbai
Date
2025-08-01  36.000000  31.666667  32.000000
2025-08-02  25.000000        NaN  28.000000
2025-08-03        NaN  29.500000  32.500000
2025-08-04  37.000000  27.000000        NaN
2025-08-05  30.750000  29.000000        NaN
2025-08-06  34.750000  27.000000        NaN
2025-08-07  33.000000  30.666667  25.000000
2025-08-08  33.000000        NaN  27.000000
2025-08-09  36.000000  33.000000  31.333333
2025-08-10  29.000000  30.666667        NaN
2025-08-11        NaN  37.000000  31.000000
2025-08-12  36.500000        NaN  31.250000
2025-08-13  31.666667        NaN  34.000000
2025-08-14  28.000000  39.000000        NaN
2025-08-15  28.500000        NaN  29.333333

In [ ]:
data.pivot_table(index='City',columns='Date',aggfunc='sum')

            Humidity                                                         \
Date      2025-08-01 2025-08-02 2025-08-03 2025-08-04 2025-08-05 2025-08-06
City
Bengaluru       86.0       71.0        NaN       87.0      262.0      298.0
Delhi          239.0        NaN       39.0      122.0      158.0      124.0
Mumbai         184.0      134.0       76.0        NaN        NaN       51.0

                                                       ... Wind Speed (km/h)  \
Date      2025-08-07 2025-08-08 2025-08-09 2025-08-10  ...        2025-08-06
City                                                   ...
Bengaluru      151.0        0.0      161.0      131.0  ...              38.0
Delhi          209.0        NaN      152.0      165.0  ...              36.0
Mumbai          78.0      198.0      233.0        NaN  ...               7.0

                                                                             \
Date      2025-08-07 2025-08-08 2025-08-09 2025-08-10 2025-08-11 2025-08-12
City
Bengaluru       31.0       46.0       39.0       30.0        NaN       34.0
Delhi           38.0        NaN       21.0       33.0       20.0        6.0
Mumbai          14.0       43.0       39.0        NaN       21.0       31.0


Date      2025-08-13 2025-08-14 2025-08-15
City
Bengaluru       24.0       32.0       29.0
Delhi           17.0       22.0        NaN
Mumbai          22.0        NaN       32.0

[3 rows x 60 columns]

In [ ]:
data.pivot_table(index='City',columns='Date' ,aggfunc='sum',margins=True)

            Humidity                                                         \
Date      2025-08-01 2025-08-02 2025-08-03 2025-08-04 2025-08-05 2025-08-06
City
Bengaluru       86.0       71.0        NaN       87.0      262.0      298.0
Delhi          239.0        NaN       39.0      122.0      158.0      124.0
Mumbai         184.0      134.0       76.0        NaN        NaN       51.0
All            423.0      145.0       39.0      142.0      235.0      339.0

                                                       ... Wind Speed (km/h)  \
Date      2025-08-07 2025-08-08 2025-08-09 2025-08-10  ...        2025-08-07
City                                                   ...
Bengaluru      151.0        0.0      161.0      131.0  ...              31.0
Delhi          209.0        NaN      152.0      165.0  ...              38.0
Mumbai          78.0      198.0      233.0        NaN  ...              14.0
All            307.0      198.0      276.0      122.0  ...              68.0

                                                                             \
Date      2025-08-08 2025-08-09 2025-08-10 2025-08-11 2025-08-12 2025-08-13
City
Bengaluru       46.0       39.0       30.0        NaN       34.0       24.0
Delhi            NaN       21.0       33.0       20.0        6.0       17.0
Mumbai          43.0       39.0        NaN       21.0       31.0       22.0
All             43.0       67.0       37.0       41.0       41.0       38.0


Date      2025-08-14 2025-08-15    All
City
Bengaluru       32.0       29.0  255.0
Delhi           22.0        NaN  177.0
Mumbai           NaN       32.0  233.0
All             23.0       52.0  665.0

[4 rows x 64 columns]

pivot grouper

In [ ]:
import pandas as pd

# Load dataset
df = pd.read_csv('/content/sales_data.csv')
df

   OrderID        Date     Category     Product  Quantity  Price
0     1001  2023-01-15  Electronics      Laptop         2  70000
1     1002  2023-01-20    Furniture       Chair         4   1500
2     1003  2023-02-05  Electronics  Headphones         5   2000
3     1004  2023-02-18    Furniture       Table         1   5000
4     1005  2023-03-03   Stationery    Notebook        10     50
5     1006  2023-03-25  Electronics       Mouse         6    800
6     1007  2023-04-10    Furniture        Sofa         1  15000
7     1008  2023-04-15   Stationery         Pen        20     20
8     1009  2023-05-01  Electronics      Laptop         1  70000
9     1010  2023-05-12    Furniture       Chair         2   1500

In [ ]:
# Add total sales column
df['Total'] = df['Quantity'] * df['Price']
df

   OrderID        Date     Category     Product  Quantity  Price   Total
0     1001  2023-01-15  Electronics      Laptop         2  70000  140000
1     1002  2023-01-20    Furniture       Chair         4   1500    6000
2     1003  2023-02-05  Electronics  Headphones         5   2000   10000
3     1004  2023-02-18    Furniture       Table         1   5000    5000
4     1005  2023-03-03   Stationery    Notebook        10     50     500
5     1006  2023-03-25  Electronics       Mouse         6    800    4800
6     1007  2023-04-10    Furniture        Sofa         1  15000   15000
7     1008  2023-04-15   Stationery         Pen        20     20     400
8     1009  2023-05-01  Electronics      Laptop         1  70000   70000
9     1010  2023-05-12    Furniture       Chair         2   1500    3000

In [ ]:
# Create pivot table with Grouper (monthly)
df['Date'] = pd.to_datetime(df['Date'])
pivot = pd.pivot_table(
    df,
    index=pd.Grouper(key='Date', freq='M'),
    columns='Category',
    values='Total',
    aggfunc='sum'
)

pivot

/tmp/ipython-input-786410142.py:5: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  index=pd.Grouper(key='Date', freq='M'),

Category    Electronics  Furniture  Stationery
Date
2023-01-31     140000.0     6000.0         NaN
2023-02-28      10000.0     5000.0         NaN
2023-03-31       4800.0        NaN       500.0
2023-04-30          NaN    15000.0       400.0
2023-05-31      70000.0     3000.0         NaN

Melt(Melt allows to transform or reshape the data frame)

In [ ]:
import pandas as pd

# Creating the dataset
data = {
    'Date': ['2025-08-01', '2025-08-01', '2025-08-01',
             '2025-08-02', '2025-08-02', '2025-08-02',
             '2025-08-03', '2025-08-03', '2025-08-03'],
    'City': ['Mumbai', 'Delhi', 'Bengaluru',
             'Mumbai', 'Delhi', 'Bengaluru',
             'Mumbai', 'Delhi', 'Bengaluru'],
    'Temperature': [30, 36, 27, 29, 35, 26, 28, 34, 27],
    'Humidity': [85, 40, 70, 88, 45, 72, 90, 50, 68],
    'Wind Speed (km/h)': [12, 18, 10, 14, 20, 9, 11, 22, 8],
    'Weather Condition': ['Rainy', 'Sunny', 'Cloudy',
                          'Rainy', 'Sunny', 'Cloudy',
                          'Rainy', 'Partly Cloudy', 'Cloudy']
}

# Creating the DataFrame
df = pd.DataFrame(data)
df

,Date,City,Temperature,Humidity,Wind Speed (km/h),Weather Condition
0,2025-08-01,Mumbai,30,85,12,Rainy
1,2025-08-01,Delhi,36,40,18,Sunny
2,2025-08-01,Bengaluru,27,70,10,Cloudy
3,2025-08-02,Mumbai,29,88,14,Rainy
4,2025-08-02,Delhi,35,45,20,Sunny
5,2025-08-02,Bengaluru,26,72,9,Cloudy
6,2025-08-03,Mumbai,28,90,11,Rainy
7,2025-08-03,Delhi,34,50,22,Partly Cloudy
8,2025-08-03,Bengaluru,27,68,8,Cloudy

In [ ]:
pd.melt(df,id_vars=['Date'])

          Date           variable          value
0   2025-08-01               City         Mumbai
1   2025-08-01               City          Delhi
2   2025-08-01               City      Bengaluru
3   2025-08-02               City         Mumbai
4   2025-08-02               City          Delhi
5   2025-08-02               City      Bengaluru
6   2025-08-03               City         Mumbai
7   2025-08-03               City          Delhi
8   2025-08-03               City      Bengaluru
9   2025-08-01        Temperature             30
10  2025-08-01        Temperature             36
11  2025-08-01        Temperature             27
12  2025-08-02        Temperature             29
13  2025-08-02        Temperature             35
14  2025-08-02        Temperature             26
15  2025-08-03        Temperature             28
16  2025-08-03        Temperature             34
17  2025-08-03        Temperature             27
18  2025-08-01           Humidity             85
19  2025-08-01           Humidity             40
20  2025-08-01           Humidity             70
21  2025-08-02           Humidity             88
22  2025-08-02           Humidity             45
23  2025-08-02           Humidity             72
24  2025-08-03           Humidity             90
25  2025-08-03           Humidity             50
26  2025-08-03           Humidity             68
27  2025-08-01  Wind Speed (km/h)             12
28  2025-08-01  Wind Speed (km/h)             18
29  2025-08-01  Wind Speed (km/h)             10
30  2025-08-02  Wind Speed (km/h)             14
31  2025-08-02  Wind Speed (km/h)             20
32  2025-08-02  Wind Speed (km/h)              9
33  2025-08-03  Wind Speed (km/h)             11
34  2025-08-03  Wind Speed (km/h)             22
35  2025-08-03  Wind Speed (km/h)              8
36  2025-08-01  Weather Condition          Rainy
37  2025-08-01  Weather Condition          Sunny
38  2025-08-01  Weather Condition         Cloudy
39  2025-08-02  Weather Condition          Rainy
40  2025-08-02  Weather Condition          Sunny
41  2025-08-02  Weather Condition         Cloudy
42  2025-08-03  Weather Condition          Rainy
43  2025-08-03  Weather Condition  Partly Cloudy
44  2025-08-03  Weather Condition         Cloudy

In [ ]:
melted = pd.melt(
    df,
    id_vars=['City', 'Date','Weather Condition'],
    value_vars=['Temperature', 'Humidity'],
    var_name='Weather_Parameter',
    value_name='Reading'
)
melted

         City        Date Weather Condition Weather_Parameter  Reading
0      Mumbai  2025-08-01             Rainy       Temperature       30
1       Delhi  2025-08-01             Sunny       Temperature       36
2   Bengaluru  2025-08-01            Cloudy       Temperature       27
3      Mumbai  2025-08-02             Rainy       Temperature       29
4       Delhi  2025-08-02             Sunny       Temperature       35
5   Bengaluru  2025-08-02            Cloudy       Temperature       26
6      Mumbai  2025-08-03             Rainy       Temperature       28
7       Delhi  2025-08-03     Partly Cloudy       Temperature       34
8   Bengaluru  2025-08-03            Cloudy       Temperature       27
9      Mumbai  2025-08-01             Rainy          Humidity       85
10      Delhi  2025-08-01             Sunny          Humidity       40
11  Bengaluru  2025-08-01            Cloudy          Humidity       70
12     Mumbai  2025-08-02             Rainy          Humidity       88
13      Delhi  2025-08-02             Sunny          Humidity       45
14  Bengaluru  2025-08-02            Cloudy          Humidity       72
15     Mumbai  2025-08-03             Rainy          Humidity       90
16      Delhi  2025-08-03     Partly Cloudy          Humidity       50
17  Bengaluru  2025-08-03            Cloudy          Humidity       68

Cross tab or contingency table

In [ ]:
import pandas as pd

# Defining the dataset
data = {
    'RespondentID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female'],
    'AgeGroup': ['18-25', '26-35', '18-25', '18-25', '26-35', '18-25', '36-45', '26-35', '26-35', '36-45'],
    'Preferred_Device': ['Laptop', 'Mobile', 'Tablet', 'Mobile', 'Laptop', 'Mobile', 'Laptop', 'Tablet', 'Mobile', 'Laptop']
}

# Creating the DataFrame
df = pd.DataFrame(data)
df

   RespondentID  Gender AgeGroup Preferred_Device
0             1    Male    18-25           Laptop
1             2  Female    26-35           Mobile
2             3    Male    18-25           Tablet
3             4  Female    18-25           Mobile
4             5    Male    26-35           Laptop
5             6  Female    18-25           Mobile
6             7    Male    36-45           Laptop
7             8  Female    26-35           Tablet
8             9    Male    26-35           Mobile
9            10  Female    36-45           Laptop

In [ ]:

# Cross-tab of AgeGroup vs Preferred_Device with totals:

ct2 = pd.crosstab(df['AgeGroup'], df['Preferred_Device'], margins=True, margins_name='Total')
print(ct2)

Preferred_Device  Laptop  Mobile  Tablet  Total
AgeGroup
18-25                  1       2       1      4
26-35                  1       2       1      4
36-45                  2       0       0      2
Total                  4       4       2     10

to_datetime()

In [ ]:
import pandas as pd
pd.to_datetime(['05/01/2017'], dayfirst=True)

DatetimeIndex(['2017-01-05'], dtype='datetime64[ns]', freq=None)

In [ ]:
dates = ['2023-01-01', 'invalid_date', '2023-03-30']
pd.to_datetime(dates, errors='coerce')

DatetimeIndex(['2023-01-01', 'NaT', '2023-03-30'], dtype='datetime64[ns]', freq=None)

In [ ]:
df

,Date,City,Temperature,Humidity,Wind Speed (km/h),Weather Condition
0,2025-08-01,Mumbai,30,85,12,Rainy
1,2025-08-01,Delhi,36,40,18,Sunny
2,2025-08-01,Bengaluru,27,70,10,Cloudy
3,2025-08-02,Mumbai,29,88,14,Rainy
4,2025-08-02,Delhi,35,45,20,Sunny
5,2025-08-02,Bengaluru,26,72,9,Cloudy
6,2025-08-03,Mumbai,28,90,11,Rainy
7,2025-08-03,Delhi,34,50,22,Partly Cloudy
8,2025-08-03,Bengaluru,27,68,8,Cloudy

In [ ]:
print("Original DataFrame:")
print(df)

Original DataFrame:
         Date       City  Temperature  Humidity  Wind Speed (km/h)  \
0  2025-08-01     Mumbai           30        85                 12
1  2025-08-01      Delhi           36        40                 18
2  2025-08-01  Bengaluru           27        70                 10
3  2025-08-02     Mumbai           29        88                 14
4  2025-08-02      Delhi           35        45                 20
5  2025-08-02  Bengaluru           26        72                  9
6  2025-08-03     Mumbai           28        90                 11
7  2025-08-03      Delhi           34        50                 22
8  2025-08-03  Bengaluru           27        68                  8

  Weather Condition
0             Rainy
1             Sunny
2            Cloudy
3             Rainy
4             Sunny
5            Cloudy
6             Rainy
7     Partly Cloudy
8            Cloudy